--01-00-ssis-pkg-01-01-scd-type-2
-- Type 2 updates

CREATE TABLE #DimProduct (
  [MergeAction] varchar(10) NULL,
  [Name] [nvarchar](50) NULL,
  [rowguid] [uniqueidentifier] NULL,
  [ModifiedDate] [datetime] NULL,
  [ProductSubcategoryID] [int] NULL,
  [ProductID] [nvarchar](25) NULL,
  [ProductNumber] [nvarchar](25) NULL,
  [MakeFlag] [bit] NULL,
  [FinishedGoodsFlag] [bit] NULL,
  [Color] [nvarchar](15) NULL,
  [SafetyStockLevel] [smallint] NULL,
  [ReorderPoint] [smallint] NULL,
  [StandardCost] [money] NULL,
  [ListPrice] [money] NULL,
  [Size] [nvarchar](5) NULL,
  [SizeUnitMeasureCode] [nvarchar](3) NULL,
  [WeightUnitMeasureCode] [nvarchar](3) NULL,
  [Weight] [numeric](8, 2) NULL,
  [DaysToManufacture] [int] NULL,
  [ProductLine] [nvarchar](2) NULL,
  [Class] [nvarchar](2) NULL,
  [Style] [nvarchar](2) NULL,
  [ProductModelID] [int] NULL,
  [SellStartDate] [datetime] NULL,
  [SellEndDate] [datetime] NULL,
  [DiscontinuedDate] [datetime] NULL,
  [AuditKey] [int] NULL,
  [ProductSubcategoryKey] [int] NULL
)
INSERT INTO #DimProduct
  SELECT
    *
  FROM (MERGE dw.DimProduct AS target USING (SELECT
    Name,
    rowguid,
    ModifiedDate,
    ProductSubcategoryID,
    ProductID,
    ProductNumber,
    MakeFlag,
    FinishedGoodsFlag,
    Color,
    SafetyStockLevel,
    ReorderPoint,
    StandardCost,
    ListPrice,
    SIZE,
    SizeUnitMeasureCode,
    WeightUnitMeasureCode,
    Weight,
    DaysToManufacture,
    ProductLine,
    CLASS,
    Style,
    ProductModelID,
    SellStartDate,
    SellEndDate,
    DiscontinuedDate,
    AuditKey,
    ProductSubcategoryKey
  FROM AdventureWorksDW_stage_demo.tmp.scdProduct) AS SOURCE ON target.ProductAlternateKey = SOURCE.ProductNumber
  AND target.Status = 'Current' WHEN MATCHED
  AND NOT (SOURCE.ListPrice = ISNULL(target.ListPrice, '')) THEN UPDATE
  SET target.Status = NULL, target.EndDate = GETDATE() WHEN NOT MATCHED BY target
  AND SOURCE.SellEndDate IS NULL THEN INSERT (ProductAlternateKey,
  ProductSubcategoryKey,
  WeightUnitMeasureCode,
  SizeUnitMeasureCode,
  EnglishProductName,
  SpanishProductName,
  FrenchProductName,
  StandardCost,
  FinishedGoodsFlag,
  Color,
  SafetyStockLevel,
  ReorderPoint,
  ListPrice,
  SIZE,
  SizeRange,
  [Weight],
  DaysToManufacture,
  ProductLine,
  DealerPrice,
  CLASS,
  Style,
  ModelName,
  LargePhoto,
  EnglishDescription,
  FrenchDescription,
  ChineseDescription,
  ArabicDescription,
  HebrewDescription,
  ThaiDescription,
  GermanDescription,
  JapaneseDescription,
  TurkishDescription,
  StartDate,
  EndDate,
  [Status],
  AuditKey)
  VALUES (SOURCE.ProductNumber,
  SOURCE.ProductSubcategoryKey,
  SOURCE.WeightUnitMeasureCode,
  SOURCE.SizeUnitMeasureCode,
  SOURCE.Name,
  '',
  '',
  SOURCE.StandardCost,
  SOURCE.FinishedGoodsFlag,
  ISNULL(SOURCE.Color, ''),
  SOURCE.SafetyStockLevel,
  SOURCE.ReorderPoint,
  SOURCE.ListPrice,
  SOURCE.SIZE,
  NULL,
  SOURCE.[Weight],
  SOURCE.DaysToManufacture,
  SOURCE.ProductLine,
  NULL,
  SOURCE.CLASS,
  SOURCE.Style,
  SOURCE.Name,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  GETDATE(),
  NULL,
  'Current',
  SOURCE.AuditKey) OUTPUT $ACTION AS mergeAction,
  SOURCE.*) mergeOutput;

INSERT INTO dw.DimProduct
SELECT ProductNumber,
  ProductSubcategoryKey,
  WeightUnitMeasureCode,
  SizeUnitMeasureCode,
  Name,
  '',
  '',
  StandardCost,
  FinishedGoodsFlag,
  Color,
  SafetyStockLevel,
  ReorderPoint,
  ListPrice,
  SIZE,
  NULL,
  [Weight],
  DaysToManufacture,
  ProductLine,
  NULL,
  CLASS,
  Style,
  Name,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  GETDATE(),
  NULL,
  'Current',
  AuditKey  FROM #DimProduct 
   WHERE MergeAction = 'UPDATE'

SELECT
  SUM(CASE
    WHEN MergeAction IN ('INSERT', 'UPDATE') THEN 1
    ELSE 0
  END) AS RowCountInsert,
  SUM(CASE
    WHEN MergeAction = 'UPDATE' THEN 1
    ELSE 0
  END) AS RowCountUpdate
FROM #DimProduct