let
    StartDate = #date(2010,1,1),
    EndDate = #date(2017,12,31),
    //use slashes to write comments, to make your code more readable to others
    GetDaysCount = Duration.Days(EndDate-StartDate),
    GetDateList = List.Dates(StartDate,GetDaysCount,#duration(1,0,0,0)),
    #"Converted to Table" = Table.FromList(GetDateList, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "Date"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Date", type date}}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "Date", "Date - Copy"),
    #"Renamed Columns1" = Table.RenameColumns(#"Duplicated Column",{{"Date - Copy", "MonthName"}}),
    #"Extracted Month Name" = Table.TransformColumns(#"Renamed Columns1", {{"MonthName", each Date.MonthName(_), type text}}),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Extracted Month Name", "Date", "Date - Copy"),
    #"Extracted Month" = Table.TransformColumns(#"Duplicated Column1",{{"Date - Copy", Date.Month}}),
    #"Renamed Columns2" = Table.RenameColumns(#"Extracted Month",{{"Date - Copy", "MonthNumberOfTheYear"}}),
    #"Duplicated Column2" = Table.DuplicateColumn(#"Renamed Columns2", "Date", "Date - Copy"),
    #"Renamed Columns3" = Table.RenameColumns(#"Duplicated Column2",{{"Date - Copy", "EnglishDayName"}}),
    #"Extracted Day Name" = Table.TransformColumns(#"Renamed Columns3", {{"EnglishDayName", each Date.DayOfWeekName(_), type text}}),
    #"Duplicated Column3" = Table.DuplicateColumn(#"Extracted Day Name", "Date", "Date - Copy"),
    #"Renamed Columns4" = Table.RenameColumns(#"Duplicated Column3",{{"Date - Copy", "DayNumberOfWeek"}}),
    #"Calculated Day of Week" = Table.TransformColumns(#"Renamed Columns4",{{"DayNumberOfWeek", Date.DayOfWeek}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Calculated Day of Week",{{"DayNumberOfWeek", Int64.Type}})
in
  #"Changed Type1"
