let
    StartDate = #datetime(2018,1,1,0,0,0),
    EndDate = #datetime(2022,12,31,23,59,0),
    MinsCount = Duration.TotalMinutes(Duration.From(EndDate - StartDate)),
    ListMins = List.DateTimes(StartDate,MinsCount,#duration(0,0,1,0)),
    #"Converted to Table" = Table.FromList(ListMins, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Renamed Columns" = Table.RenameColumns(#"Converted to Table",{{"Column1", "DateIme"}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"DateIme", type datetime}}),
    #"Duplicated Column" = Table.DuplicateColumn(#"Changed Type", "DateIme", "DateIme - Copy"),
    #"Extracted Year" = Table.TransformColumns(#"Duplicated Column",{{"DateIme - Copy", Date.Year, Int64.Type}}),
    #"Renamed Columns1" = Table.RenameColumns(#"Extracted Year",{{"DateIme - Copy", "Year"}}),
    #"Duplicated Column1" = Table.DuplicateColumn(#"Renamed Columns1", "DateIme", "DateIme - Copy"),
    #"Renamed Columns2" = Table.RenameColumns(#"Duplicated Column1",{{"DateIme - Copy", "MonthNumber"}}),
    #"Extracted Month" = Table.TransformColumns(#"Renamed Columns2",{{"MonthNumber", Date.Month, Int64.Type}}),
    #"Duplicated Column2" = Table.DuplicateColumn(#"Extracted Month", "DateIme", "DateIme - Copy"),
    #"Renamed Columns3" = Table.RenameColumns(#"Duplicated Column2",{{"DateIme - Copy", "MonthName"}}),
    #"Extracted Month Name" = Table.TransformColumns(#"Renamed Columns3", {{"MonthName", each Date.MonthName(_), type text}}),
    #"Duplicated Column3" = Table.DuplicateColumn(#"Extracted Month Name", "DateIme", "DateIme - Copy"),
    #"Renamed Columns4" = Table.RenameColumns(#"Duplicated Column3",{{"DateIme - Copy", "DayNumber"}}),
    #"Extracted Day" = Table.TransformColumns(#"Renamed Columns4",{{"DayNumber", Date.Day, Int64.Type}}),
    #"Duplicated Column4" = Table.DuplicateColumn(#"Extracted Day", "DateIme", "DateIme - Copy"),
    #"Renamed Columns5" = Table.RenameColumns(#"Duplicated Column4",{{"DateIme - Copy", "Hour"}}),
    #"Extracted Hour" = Table.TransformColumns(#"Renamed Columns5",{{"Hour", Time.Hour, Int64.Type}}),
    #"Duplicated Column5" = Table.DuplicateColumn(#"Extracted Hour", "DateIme", "DateIme - Copy"),
    #"Renamed Columns6" = Table.RenameColumns(#"Duplicated Column5",{{"DateIme - Copy", "Minute"}}),
    #"Extracted Minute" = Table.TransformColumns(#"Renamed Columns6",{{"Minute", Time.Minute, Int64.Type}}),
    #"Renamed Columns7" = Table.RenameColumns(#"Extracted Minute",{{"DateIme", "DateTime"}}),
    #"Added Custom" = Table.AddColumn(#"Renamed Columns7", "YearMonthDayHHMM", each Number.ToText([Year])&""&Text.End("0"&Number.ToText([MonthNumber]),2)&""&Text.End("0"&Number.ToText([DayNumber]),2)&""&Text.End("0"&Number.ToText([Hour]),2)&""&Text.End("0"&Number.ToText([Minute]),2)),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"YearMonthDayHHMM", type text}}),
    #"Added Conditional Column" = Table.AddColumn(#"Changed Type1", "MinuteBin", each if [Minute] <= 30 then 00 else 30),
    #"Changed Type2" = Table.TransformColumnTypes(#"Added Conditional Column",{{"MinuteBin", type text}}),
    #"Added Custom1" = Table.AddColumn(#"Changed Type2", "MinuteBinDer", each Text.End("0"&([MinuteBin]),2)),
    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom1",{{"MinuteBinDer", type text}}),
    #"Added Custom2" = Table.AddColumn(#"Changed Type3", "HourBin", each Text.End("0"&Number.ToText([Hour]),2)),
    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom2",{{"HourBin", type text}}),
    #"Added Custom3" = Table.AddColumn(#"Changed Type4", "HourMin30MinBin", each [HourBin]&":"&[MinuteBinDer]),
    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom3",{{"HourMin30MinBin", type text}})
in
    #"Changed Type5"
